### Site metadata

title: Max Jeremy
description: Mackie's portfolio

url: "https://artists-portfolio.netlify.app"
baseurl: ""

github_username: "samdeverett"
repository: "samdeverett/mackie"

google_analytics_key: ""

# For SEO tag.
logo:
author:
  name:
  twitter:
social:
  name:
  links:

### Build settings

timezone: Etc/UTC

permalink: pretty

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      text_width: true
  - scope:
      path: "index.html"
    values:
      text_width: false

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - README.md
  - LICENSE
  - LICENCE-source
  - Makefile
  - netlify.toml
